version: '3'
services:
  ubuntu:
    build: ./docker/ubuntu
    image: local/ubuntu
  nodejs-deps:
    build: ./docker/nodejs-deps
    image: local/nodejs-deps
    depends_on:
      - ubuntu
  nodejs:
    build: ./docker/nodejs
    image: local/nodejs
    depends_on:
      - nodejs-deps
  server:
    build: ./server
    depends_on:
      - nodejs
    command: bash -c 'yarn install && yarn start'
    ports:
      - '9000:9000'
    volumes:
      - './server:/www/'
      - '/www/node_modules'
  client:
    build: ./client
    depends_on:
      - server
    environment:
      - NODE_ENV=$NODE_ENV
      - HOST=$HOST
    command: bash -c 'yarn install && yarn dev'
    ports:
      - '8000:8000'
    volumes:
      - './client:/www/'
      - '/www/node_modules'
