version: '3'
services:
  nodejs:
    build: ./docker/nodejs
    image: local/nodejs
  server:
    build: ./server
    depends_on:
      - nodejs
    command: bash -c 'yarn install && yarn start'
    ports:
      - '9000:9000'
    volumes:
      - './server:/www/'
      - '/www/node_modules'
  web:
    build: ./web
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - API_HOST=http://localhost:9000
    command: bash -c 'yarn install && yarn dev'
    ports:
      - '8000:8000'
    volumes:
      - './web:/www/'
      - '/www/node_modules'
